### ISSUE TITLE
That's a cool idea

### ISSUE THREAD

**Issue by krysalead** [cbrintnall/shorter.recipes#6]
Hi,

I found your link on Redit and I was just happy to see what you had in mind
I developed the same thing 4 years ago but only targeting French website.
I think we have the same motivation and I would love to see if we can't merge our 2 projects in a super project?
I have a backend in Microservice so we can easily integrate work in various technologies (I am a nodejs developer).
My application is going a bit farer by adding smart tooling on top of the parsing. I would love to explain all of that if you wish.
krysalead@gmail.com

K

**Comment by cbrintnall** [comment]
Hi @krysalead, this isn't the place to post something like this. Please reach out to my e-mail (on my Github profile) for inquiries like this.

Theres also a feedback button on https://shorter.recipes.

**Comment by krysalead** [comment]
Hi,

Sorry for contacting you like that and now I realised that I shouldn't have posted my url and only give you some contact info. Up to you to learn more about me. I did that because your email is not visible in your profile otherwise you will have received an email instead.

Regards

Krys
